# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql2
  database: town_of_dayton
  host: localhost
  username: root
  password: 

test:
  adapter: mysql
  database: town_of_dayton_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  database: daytonva
  host: localhost
  username: root
  password: foundL0v3sD@yton
