require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmailContentsController do

  # This should return the minimal set of attributes required to create a valid
  # EmailContent. As you add validations to EmailContent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all email_contents as @email_contents" do
      email_content = EmailContent.create! valid_attributes
      get :index
      assigns(:email_contents).should eq([email_content])
    end
  end

  describe "GET show" do
    it "assigns the requested email_content as @email_content" do
      email_content = EmailContent.create! valid_attributes
      get :show, :id => email_content.id.to_s
      assigns(:email_content).should eq(email_content)
    end
  end

  describe "GET new" do
    it "assigns a new email_content as @email_content" do
      get :new
      assigns(:email_content).should be_a_new(EmailContent)
    end
  end

  describe "GET edit" do
    it "assigns the requested email_content as @email_content" do
      email_content = EmailContent.create! valid_attributes
      get :edit, :id => email_content.id.to_s
      assigns(:email_content).should eq(email_content)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmailContent" do
        expect {
          post :create, :email_content => valid_attributes
        }.to change(EmailContent, :count).by(1)
      end

      it "assigns a newly created email_content as @email_content" do
        post :create, :email_content => valid_attributes
        assigns(:email_content).should be_a(EmailContent)
        assigns(:email_content).should be_persisted
      end

      it "redirects to the created email_content" do
        post :create, :email_content => valid_attributes
        response.should redirect_to(EmailContent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved email_content as @email_content" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmailContent.any_instance.stub(:save).and_return(false)
        post :create, :email_content => {}
        assigns(:email_content).should be_a_new(EmailContent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmailContent.any_instance.stub(:save).and_return(false)
        post :create, :email_content => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested email_content" do
        email_content = EmailContent.create! valid_attributes
        # Assuming there are no other email_contents in the database, this
        # specifies that the EmailContent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmailContent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => email_content.id, :email_content => {'these' => 'params'}
      end

      it "assigns the requested email_content as @email_content" do
        email_content = EmailContent.create! valid_attributes
        put :update, :id => email_content.id, :email_content => valid_attributes
        assigns(:email_content).should eq(email_content)
      end

      it "redirects to the email_content" do
        email_content = EmailContent.create! valid_attributes
        put :update, :id => email_content.id, :email_content => valid_attributes
        response.should redirect_to(email_content)
      end
    end

    describe "with invalid params" do
      it "assigns the email_content as @email_content" do
        email_content = EmailContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmailContent.any_instance.stub(:save).and_return(false)
        put :update, :id => email_content.id.to_s, :email_content => {}
        assigns(:email_content).should eq(email_content)
      end

      it "re-renders the 'edit' template" do
        email_content = EmailContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmailContent.any_instance.stub(:save).and_return(false)
        put :update, :id => email_content.id.to_s, :email_content => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested email_content" do
      email_content = EmailContent.create! valid_attributes
      expect {
        delete :destroy, :id => email_content.id.to_s
      }.to change(EmailContent, :count).by(-1)
    end

    it "redirects to the email_contents list" do
      email_content = EmailContent.create! valid_attributes
      delete :destroy, :id => email_content.id.to_s
      response.should redirect_to(email_contents_url)
    end
  end

end
